---
- hosts: all
  become: yes
  gather_facts: no
  tasks: 
  - name: install  git, tree and wget on ubuntu16
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - git
     - tree
     - wget