---
- hosts: amazonos
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    yum:
      name: httpd
      state: present

  - name: start the service
    service:
      name: httpd
      state: started

  